### PR TITLE
Allow orders to be edited and deleted.

### PR DESCRIPTION
**Pull request by capnfabs**
Also, adds comprehensive tests for OrdersResource.

### CODE REVIEW

**Comment by llvasconcellos** [comment]
Good to go!

**Comment by capnfabs** [comment]
Ok, please take another look at the second commit here; I switched back to an architecture closer to what Ping had implemented initially.

**Comment by llvasconcellos** [comment]
OK. Only one comment but it's fine by me.

**Comment by capnfabs** [comment]
Thanks!

**Pull request merged**
