### PR TITLE
Enable interval=0 to disable merging.

### PR DESCRIPTION
**Pull request by llvasconcellos**

### CODE REVIEW

**Comment by capnfabs** [comment]
As written, wouldn't this cause all observations to merge with `interval=0`?

**Comment by llvasconcellos** [comment]
It shouldn't. But I'm doing a really careful test now.

**Comment by llvasconcellos** [comment]
@capnfabs Now CSV Exports is more reliable and interval=0 really disables merging.

**Comment by llvasconcellos** [comment]
@capnfabs I'm merging this as Dan tested it and it's working as desired. If you review it and have any comments regarding the code let me know and I'll fix it.

**Comment by capnfabs** [comment]
:+1:

**Pull request merged**
