### PR TITLE
Allow concept types to be changed by profile_apply script

### PR DESCRIPTION
**Pull request by capnfabs**
DO NOT MERGE

This what I had to do to apply dev.projectbuendia.org's current profile locally.

### CODE REVIEW

**Comment by llvasconcellos** [comment]
I'm lost regarding to profile_apply. I can't be of any help by now.

**Comment by capnfabs** [comment]
No worries. Like what @viniciusboson was saying in standup, I'm not sure that this is the right thing to do - probably better to work out how to use these concepts correctly rather than just do this :)

I'm just trying to document what's required so that if people get stuck in the future they've got options.

**Comment by viniciusboson** [comment]
Just to be documented as well, [here is more comments](https://github.com/projectbuendia/client/issues/53#issuecomment-152531404) of that, on #53.

**Comment by capnfabs** [comment]
Nice! I'd missed that before. Thanks @viniciusboson

**Pull request closed without merging**
