### PR TITLE
Fixed directory ownership and permissions.

### PR DESCRIPTION
**Pull request by llvasconcellos**

### CODE REVIEW

**Comment by llvasconcellos** [comment]
On Linux $current_user without the quotes, I tested it. I kept the ownership to root because he is the creator of the directory (using sudo) and I added the user group to the directory. That was the intention.
All users are created with a group with his name, so my user is leonardo and one of my groups is leonardo by default (along side with sudoers and others). This is the default behavior for Linux (at least Debian). 
I wanted to keep root as the owner to maintain consistency with the others directories in the /usr/share but there is no other reason.

**Comment by llvasconcellos** [comment]
Ok. Now it should be good to go!

**Comment by capnfabs** [comment]
Thanks! For a bit more information, when I run `groups` on Mac I get:

```
staff
access_bpf
com.apple.sharepoint.group.1
everyone
localaccounts
_appserverusr
admin
_appserveradm
_lpadmin
_appstore
_lpoperator
_developer
com.apple.access_ftp
com.apple.access_screensharing
com.apple.access_ssh
```

Note the absence of a `fabian` group (my username).

**Comment by llvasconcellos** [comment]
@capnfabs look mine:
```bash
;) [leonardo@samsung ~/Projects/Buendia/client] $ groups
leonardo adm cdrom sudo dip plugdev lpadmin sambashare libvirtd
```

**Pull request merged**
